import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";
import NavigationBar from "./components/NavigationBar";
import Footer from "./components/Footer";
import { ToastProvider } from "./contexts/CustomToast";
import { CartProvider } from "./contexts/CartProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Elora Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className="" >
        <Provider>
          <CartProvider>

            <ToastProvider>
              <NavigationBar />

              {children}
              <Footer />
            </ToastProvider>
          </CartProvider>
        </Provider>
      </body>
    </html>
  );
}
